name: Mathlib bump

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: leanprover-community/mathlib-update-action@d2b8804850b44ce9be89ab9c39ad460e11e563eb  # main @ 2025-11-11
        with:
          intermediate_releases: latest
